version: '2'
services:

#PHP+Apache
  phpapache:
    build: .
    volumes:
      - ${SOURCES_ROOT}/_site:/var/www/html
    ports:
     - "8080:80"
     - "8888:8000"

#Mysql
  db:
    image: mysql:8.0.3
    restart: always
    volumes:
         - mysqlvolume:/var/lib/mysql
    environment:
         - MYSQL_ROOT_PASSWORD=example
         - MYSQL_DATABASE=diplom
         - MYSQL_USER=user
         - MYSQL_PASSWORD=password

  adminer:
      image: adminer:4.3.1-standalone
      restart: always
      ports:
          - 9000:8080

volumes:
  mysqlvolume: